import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import io, { Socket } from 'Socket.IO-client'
import { useEffect } from 'react'
import { DefaultEventsMap } from '@socket.io/component-emitter'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  let socket: Socket<DefaultEventsMap, DefaultEventsMap> | null = null;

  const socketInitializer = () => {
    socket = io('192.168.1.109:5000');

    socket.on('connect', () => {
      console.log('Connected to server');
    });
  }

  const sendForward = () => {
    socket?.emit('control', 'forward')
  }

  const sendBackward = () => {
    socket?.emit('control', 'backward')
  }

  const sendLeft = () => {
    socket?.emit('control', 'left')
  }

  const sendRight = () => {
    socket?.emit('control', 'right')
  }

  const resetMotor = () => {
    socket?.emit('control', 'reset-motor')
  }

  const resetServo = () => {
    socket?.emit('control', 'reset-servo')
  }

  useEffect(() =>{
    socketInitializer()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onMouseDown={sendForward} onMouseUp={resetMotor} >Forward</button>
        <button onMouseDown={sendBackward} onMouseUp={resetMotor} >Backward</button>
        <button onMouseDown={sendLeft} onMouseUp={resetServo} >Left</button>
        <button onMouseDown={sendRight} onMouseUp={resetServo} >Right</button>
      </main>
    </>
  )
}
